spring.application.name=execution-flow-service

# Database settings
spring.datasource.url=jdbc:h2:mem:execution_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQS and AWS settings
# For local run/tests we can override or use LocalStack.
# In production, Spring Cloud AWS automatically picks credentials/region from the environment.
spring.cloud.aws.credentials.access-key=mock-access-key
spring.cloud.aws.credentials.secret-key=mock-secret-key
spring.cloud.aws.region.static=us-east-1

# Standard App Custom Configuration
app.sqs.queue-name=order-processing-queue
